import type { UserItem, TeamItem, ClassItem } from "./types";

export const pedagogicalTeams: Record<string, { subject: string; code: string; teacher: string }[]> = {
  // Page 1
  '601': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'POTIER VIRGINIE' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'HEUSSER SUSANNE' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'ROSALES Magali' },
    { subject: 'Devoirs faits', code: 'DEV', teacher: 'LACASTA ANNE-LAURE' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'LACOSTE AUDE-MARIE' },
    { subject: 'EPS', code: 'EPS', teacher: 'JUBAULT Aurélien' },
    { subject: 'Français', code: 'FR', teacher: 'LESTANG Marie' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LACOSTE AUDE-MARIE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'GUEDJ GUILLAUME' },
    { subject: 'Sciences & Technologie', code: 'SC & TECH', teacher: 'BACQUET GILLES' },
    { subject: 'SVT', code: 'SVT', teacher: 'LABBE VERONIQUE' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'LABBE VERONIQUE' },
  ],
  '602': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'NOIREAU Jean-Christophe' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'FERNANDES PHILOMENE' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'HEUSSER SUSANNE' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'ROSALES Magali' },
    { subject: 'Devoirs faits', code: 'DEV', teacher: 'LACASTA ANNE-LAURE' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'LACOSTE AUDE-MARIE' },
    { subject: 'EPS', code: 'EPS', teacher: 'ANGUE Pascal' },
    { subject: 'Français', code: 'FR', teacher: 'LESTANG Marie' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LACOSTE AUDE-MARIE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'THIAUDE PHILIPPE' },
    { subject: 'Sciences & Technologie', code: 'SC & TECH', teacher: 'BACQUET GILLES' },
    { subject: 'SVT', code: 'SVT', teacher: 'LABBE VERONIQUE' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'FERNANDES PHILOMENE' },
  ],
  '603': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'LACASTA ANNE-LAURE' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'DIZABEAU ANNE' },
    { subject: 'Devoirs faits', code: 'DEV', teacher: 'LACASTA ANNE-LAURE' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'DIZABEAU ANNE' },
    { subject: 'EPS', code: 'EPS', teacher: 'VIALA STEPHANE' },
    { subject: 'Français', code: 'FR', teacher: 'PISON Line' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'DIZABEAU ANNE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'LACHAUX CLAUDE' },
    { subject: 'Sciences & Technologie', code: 'SC & TECH', teacher: 'BACQUET GILLES' },
    { subject: 'SVT', code: 'SVT', teacher: 'VOVARD Frédérique' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'LACHAUX CLAUDE' },
  ],
  '604': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'FERNANDES PHILOMENE' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'MAGONI Clizia' },
    { subject: 'Devoirs faits', code: 'DEV', teacher: 'LACASTA ANNE-LAURE' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'LACOSTE AUDE-MARIE' },
    { subject: 'EPS', code: 'EPS', teacher: 'ROMERO JOHAN' },
    { subject: 'Français', code: 'FR', teacher: 'BOUDIGUET Leyla' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LACOSTE AUDE-MARIE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'LACHAUX CLAUDE' },
    { subject: 'Sciences & Technologie', code: 'SC & TECH', teacher: 'VOVARD Frédérique' },
    { subject: 'SVT', code: 'SVT', teacher: 'VOVARD Frédérique' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'LACOSTE AUDE-MARIE' },
  ],
  '605': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'NOIREAU Jean-Christophe' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'PANOSSIAN LAURA' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'DIZABEAU ANNE' },
    { subject: 'Devoirs faits', code: 'DEV', teacher: 'PANOSSIAN LAURA' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'DIZABEAU ANNE' },
    { subject: 'EPS', code: 'EPS', teacher: 'QUERE JOFFREY' },
    { subject: 'Français', code: 'FR', teacher: 'LESTANG Marie' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'DIZABEAU ANNE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'GUEDJ GUILLAUME' },
    { subject: 'Sciences & Technologie', code: 'SC & TECH', teacher: 'VOVARD Frédérique' },
    { subject: 'SVT', code: 'SVT', teacher: 'VOVARD Frédérique' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'GUEDJ GUILLAUME' },
  ],

  // Page 2
  '606': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'OCONNOR Georgia' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'DIZABEAU ANNE' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'DIZABEAU ANNE' },
    { subject: 'EPS', code: 'EPS', teacher: 'JUBAULT Aurélien' },
    { subject: 'Français', code: 'FR', teacher: 'SCHWANDER OLIVIER' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'DIZABEAU ANNE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'BETSCHER Armand' },
    { subject: 'Sciences & Technologie', code: 'SC & TECH', teacher: 'CANZIAN AMADIO' },
    { subject: 'SVT', code: 'SVT', teacher: 'MAUGENDRE CAROLE' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'MAUGENDRE CAROLE' },
  ],
  '501': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'PANOSSIAN LAURA' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'HEUSSER SUSANNE' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'HOCINE Cécile' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'ROSALES Magali' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'CARRICHON Nicolas' },
    { subject: 'EPS', code: 'EPS', teacher: 'JUBAULT Aurélien' },
    { subject: 'Français', code: 'FR', teacher: 'LAHAYE NICOLAS' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'CARRICHON Nicolas' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'CORNU VALERIE' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'THELEMAQUE Christophe' },
    { subject: 'SVT', code: 'SVT', teacher: 'VOVARD Frédérique' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'CANZIAN AMADIO' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'PANOSSIAN LAURA' },
  ],
  '502': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'FERNANDES PHILOMENE' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'HEUSSER SUSANNE' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'HOCINE Cécile' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'ROSALES Magali' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'TUZUN Alexandre' },
    { subject: 'EPS', code: 'EPS', teacher: 'ANGUE Pascal' },
    { subject: 'Français', code: 'FR', teacher: 'BOUTHONNIER Rémi' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LEPENNEC JEAN' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'BONNET Sarah' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'VAGINAY FRANCINE' },
    { subject: 'SVT', code: 'SVT', teacher: 'FAUQUEMBERG Claire' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'CANZIAN AMADIO' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'FAUQUEMBERG Claire' },
  ],
  '503': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'NOIREAU Jean-Christophe' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'CHERIF HAIFA' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'HOCINE Cécile' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'ROSALES Magali' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'TUZUN Alexandre' },
    { subject: 'EPS', code: 'EPS', teacher: 'ANGUE Pascal' },
    { subject: 'Français', code: 'FR', teacher: 'SCHWANDER OLIVIER' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'TUZUN Alexandre' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'BETSCHER Armand' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'THELEMAQUE Christophe' },
    { subject: 'SVT', code: 'SVT', teacher: 'FAUQUEMBERG Claire' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'CANZIAN AMADIO' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'HOCINE Cécile' },
  ],
  '504': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'NOIREAU Jean-Christophe' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'PANOSSIAN LAURA' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'GONZALEZ Claire' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'ROSALES Magali' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'MAGONI Clizia' },
    { subject: 'EPS', code: 'EPS', teacher: 'VIALA STEPHANE' },
    { subject: 'Français', code: 'FR', teacher: 'DELPOIO Carla' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'MAGONI Clizia' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'BONNEMAIN CAROLINE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'CORNU VALERIE' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'VAGINAY FRANCINE' },
    { subject: 'SVT', code: 'SVT', teacher: 'VOVARD Frédérique' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'CANZIAN AMADIO' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'VAGINAY FRANCINE' },
  ],

  // Page 3
  '505': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'CHERIF HAIFA' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'GONZALEZ Claire' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'ROSALES Magali' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'CARRICHON Nicolas' },
    { subject: 'EPS', code: 'EPS', teacher: 'JUBAULT Aurélien' },
    { subject: 'Français', code: 'FR', teacher: 'BOUTHONNIER Rémi' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'CARRICHON Nicolas' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'BONNEMAIN CAROLINE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'BACQUET GILLES' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'VAGINAY FRANCINE' },
    { subject: 'SVT', code: 'SVT', teacher: 'VOVARD Frédérique' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'CANZIAN AMADIO' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'GONZALEZ Claire' },
  ],
  '506': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'LESURE Adrien' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'HEUSSER SUSANNE' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'GONZALEZ Claire' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'ROSALES Magali' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'MAGONI Clizia' },
    { subject: 'EPS', code: 'EPS', teacher: 'VIALA STEPHANE' },
    { subject: 'Français', code: 'FR', teacher: 'SCHWANDER OLIVIER' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'MAGONI Clizia' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'BONNEMAIN CAROLINE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'BETSCHER Armand' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'VAGINAY FRANCINE' },
    { subject: 'SVT', code: 'SVT', teacher: 'VOVARD Frédérique' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'CANZIAN AMADIO' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'LESURE Adrien' },
  ],
  '401': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'NOIREAU Jean-Christophe' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'LACASTA ANNE-LAURE' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CUSSI Adelma' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'SCHWANDER OLIVIER' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'TUZUN Alexandre' },
    { subject: 'EPS', code: 'EPS', teacher: 'ANGUE Pascal' },
    { subject: 'Français', code: 'FR', teacher: 'PISON Line' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LEPENNEC JEAN' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'RINUCCINI BEATRICE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'CORNU VALERIE' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'STOJIC ALEXANDRE' },
    { subject: 'SVT', code: 'SVT', teacher: 'MATTARD JULIEN' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'CANZIAN AMADIO' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'LACASTA ANNE-LAURE' },
  ],
  '402': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'POTIER VIRGINIE' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'MAGNE Andréa' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CERDA MUNOZ Patricia' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'SCHWANDER OLIVIER' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'DIZABEAU ANNE' },
    { subject: 'EPS', code: 'EPS', teacher: 'GIRAUDEAU Marion' },
    { subject: 'Français', code: 'FR', teacher: 'PISON Line' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'DIZABEAU ANNE' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'RINUCCINI BEATRICE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'BACQUET GILLES' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'GENIEYZ Alix' },
    { subject: 'SVT', code: 'SVT', teacher: 'MATTARD JULIEN' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'CANZIAN AMADIO' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'PISON Line' },
  ],
  '403': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'DANIEL Bertilla' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'MAGNE Andréa' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CERDA MUNOZ Patricia' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'MAGNE Andréa' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'LOUIT Nicolas' },
    { subject: 'EPS', code: 'EPS', teacher: 'VIALA STEPHANE' },
    { subject: 'Français', code: 'FR', teacher: 'LAHAYE NICOLAS' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LOUIT Nicolas' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'RINUCCINI BEATRICE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'BONNET Sarah' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'GENIEYZ Alix' },
    { subject: 'SVT', code: 'SVT', teacher: 'FAUQUEMBERG Claire' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'CANZIAN AMADIO' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'DANIEL Bertilla' },
  ],

  // Page 4
  '404': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'NOIREAU Jean-Christophe' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'CHERIF HAIFA' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'MAGNE Andréa' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CERDA MUNOZ Patricia' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'MAGNE Andréa' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'DIZABEAU ANNE' },
    { subject: 'EPS', code: 'EPS', teacher: 'VIALA STEPHANE' },
    { subject: 'Français', code: 'FR', teacher: 'RINUCCINI BEATRICE' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'DIZABEAU ANNE' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'RINUCCINI BEATRICE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'HENRIO CHRISTINE' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'STOJIC ALEXANDRE' },
    { subject: 'SVT', code: 'SVT', teacher: 'FAUQUEMBERG Claire' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'CANZIAN AMADIO' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'HENRIO CHRISTINE' },
  ],
  '405': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'LESURE Adrien' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CUSSI Adelma' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'LEPENNEC JEAN' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'LACOSTE AUDE-MARIE' },
    { subject: 'EPS', code: 'EPS', teacher: 'VIALA STEPHANE' },
    { subject: 'Français', code: 'FR', teacher: 'RINUCCINI BEATRICE' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LACOSTE AUDE-MARIE' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'RINUCCINI BEATRICE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'BONNET Sarah' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'KALCK Carine' },
    { subject: 'SVT', code: 'SVT', teacher: 'FAUQUEMBERG Claire' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'CANZIAN AMADIO' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'CUSSI Adelma' },
  ],
  '406': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'POTIER VIRGINIE' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CUSSI Adelma' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'ROSALES Magali' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EMC', code: 'EMC', teacher: 'LACOSTE AUDE-MARIE' },
    { subject: 'EPS', code: 'EPS', teacher: 'GIRAUDEAU Marion' },
    { subject: 'Français', code: 'FR', teacher: 'LAHAYE NICOLAS' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LACOSTE AUDE-MARIE' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'RINUCCINI BEATRICE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'HENRIO CHRISTINE' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'STOJIC ALEXANDRE' },
    { subject: 'SVT', code: 'SVT', teacher: 'FAUQUEMBERG Claire' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'CANZIAN AMADIO' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'POTIER VIRGINIE' },
  ],
  '301': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'PANOSSIAN LAURA' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'MAGNE Andréa' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'GONZALEZ Claire' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'LEPENNEC JEAN' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EPS', code: 'EPS', teacher: 'ROMERO JOHAN' },
    { subject: 'Français', code: 'FR', teacher: 'BOUDIGUET Leyla' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'TUZUN Alexandre' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'KUBALA JAN' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'VERMEULEN GENEVIEVE' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'THELEMAQUE Christophe' },
    { subject: 'SVT', code: 'SVT', teacher: 'MATTARD JULIEN' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'BARON Valérie' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'MATTARD JULIEN' },
  ],
  '302': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'PANOSSIAN LAURA' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'MAGNE Andréa' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'GONZALEZ Claire' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'LEPENNEC JEAN' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EPS', code: 'EPS', teacher: 'ROMERO JOHAN' },
    { subject: 'Français', code: 'FR', teacher: 'BESNARD SANDRA' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LOUIT Nicolas' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'KUBALA JAN' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'BETSCHER Armand' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'GENIEYZ Alix' },
    { subject: 'SVT', code: 'SVT', teacher: 'MATTARD JULIEN' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'BARON Valérie' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'ROMERO JOHAN' },
  ],

  // Page 5
  '303': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'CHERIF HAIFA' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CERDA MUNOZ Patricia' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'THELEMAQUE Christophe' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EPS', code: 'EPS', teacher: 'GIRAUDEAU Marion' },
    { subject: 'Français', code: 'FR', teacher: 'RINUCCINI BEATRICE' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'TUZUN Alexandre' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'KUBALA JAN' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'HENRIO CHRISTINE' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'THELEMAQUE Christophe' },
    { subject: 'SVT', code: 'SVT', teacher: 'MAUGENDRE CAROLE' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'BARON Valérie' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'RINUCCINI BEATRICE' },
  ],
  '304': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'CHERIF HAIFA' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CERDA MUNOZ Patricia' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'LEPENNEC JEAN' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EPS', code: 'EPS', teacher: 'ROMERO JOHAN' },
    { subject: 'Français', code: 'FR', teacher: 'DELPOIO Carla' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'CARRICHON Nicolas' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'RINUCCINI BEATRICE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'BACQUET GILLES' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'THELEMAQUE Christophe' },
    { subject: 'SVT', code: 'SVT', teacher: 'MAUGENDRE CAROLE' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'BARON Valérie' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'CHERIF HAIFA' },
  ],
  '305': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'LESURE Adrien' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CERDA MUNOZ Patricia' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'THELEMAQUE Christophe' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EPS', code: 'EPS', teacher: 'QUERE JOFFREY' },
    { subject: 'Français', code: 'FR', teacher: 'BESNARD SANDRA' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LOUIT Nicolas' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'RINUCCINI BEATRICE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'VERMEULEN GENEVIEVE' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'GENIEYZ Alix' },
    { subject: 'SVT', code: 'SVT', teacher: 'MAUGENDRE CAROLE' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'BARON Valérie' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'LOUIT Nicolas' },
  ],
  '306': [
    { subject: 'Arts Plastiques', code: 'A-PLA', teacher: 'PECLARD ZOE' },
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'LESURE Adrien' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'MAGNE Andréa' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'GONZALEZ Claire' },
    { subject: 'Chorale', code: 'CHOR', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'Culture religieuse', code: 'KT', teacher: 'LEPENNEC JEAN' },
    { subject: 'Éducation Musicale', code: 'EDMUS', teacher: 'ALBUQUERQUE Teresa' },
    { subject: 'EPS', code: 'EPS', teacher: 'QUERE JOFFREY' },
    { subject: 'Français', code: 'FR', teacher: 'DELPOIO Carla' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'CARRICHON Nicolas' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'RINUCCINI BEATRICE' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'BETSCHER Armand' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'THELEMAQUE Christophe' },
    { subject: 'SVT', code: 'SVT', teacher: 'MAUGENDRE CAROLE' },
    { subject: 'Technologie', code: 'TECHN', teacher: 'BARON Valérie' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'CARRICHON Nicolas' },
  ],
  '201': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'OCONNOR Georgia' },
    { subject: 'Atelier Théâtre', code: 'THEAT', teacher: 'CARRICHON Nicolas' },
    { subject: 'EPS', code: 'EPS', teacher: 'QUERE JOFFREY' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CERDA MUNOZ Patricia' },
    { subject: 'Français', code: 'FR', teacher: 'BESNARD SANDRA' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'TUZUN Alexandre' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'CORNU VALERIE' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'GENIEYZ Alix' },
    { subject: 'SES', code: 'SES', teacher: 'NALBANT CORINNE' },
    { subject: 'Sciences Numériques (SNT)', code: 'SNTEC', teacher: 'GUEDJ GUILLAUME' },
    { subject: 'SVT', code: 'SVT', teacher: 'LABBE VERONIQUE' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'CORNU VALERIE' },
  ],

  // Page 6
  '202': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'POTIER VIRGINIE' },
    { subject: 'Atelier Théâtre', code: 'THEAT', teacher: 'CARRICHON Nicolas' },
    { subject: 'EPS', code: 'EPS', teacher: 'JUBAULT Aurélien' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CUSSI Adelma' },
    { subject: 'Français', code: 'FR', teacher: 'BOUTHONNIER Rémi' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'PRIOUX Charles' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'LACHAUX CLAUDE' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'STOJIC ALEXANDRE' },
    { subject: 'SES', code: 'SES', teacher: 'LANDRY Natacha' },
    { subject: 'Sciences Numériques (SNT)', code: 'SNTEC', teacher: 'GUEDJ GUILLAUME' },
    { subject: 'SVT', code: 'SVT', teacher: 'FAUQUEMBERG Claire' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'LANDRY Natacha' },
  ],
  '203': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'OCONNOR Georgia' },
    { subject: 'Atelier Théâtre', code: 'THEAT', teacher: 'CARRICHON Nicolas' },
    { subject: 'Cinéma-Audiovisuel', code: 'CI-AV', teacher: 'LAHAYE NICOLAS' },
    { subject: 'EPS', code: 'EPS', teacher: 'ROMERO JOHAN' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CERDA MUNOZ Patricia' },
    { subject: 'Français', code: 'FR', teacher: 'DELPOIO Carla' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'TUZUN Alexandre' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'KUBALA JAN' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'HENRIO CHRISTINE' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'MAHAUT Fabien' },
    { subject: 'SES', code: 'SES', teacher: 'LANDRY Natacha' },
    { subject: 'Sciences Numériques (SNT)', code: 'SNTEC', teacher: 'GUEDJ GUILLAUME' },
    { subject: 'SVT', code: 'SVT', teacher: 'FAUQUEMBERG Claire' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'DELPOIO Carla' },
  ],
  '204': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'DANIEL Bertilla' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'MAGNE Andréa' },
    { subject: 'Atelier Théâtre', code: 'THEAT', teacher: 'CARRICHON Nicolas' },
    { subject: 'EPS', code: 'EPS', teacher: 'JUBAULT Aurélien' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CUSSI Adelma' },
    { subject: 'Français', code: 'FR', teacher: 'PISON Line' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'PRIOUX Charles' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'KUBALA JAN' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'BONNET Sarah' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'GENIEYZ Alix' },
    { subject: 'SES', code: 'SES', teacher: 'LANDRY Natacha' },
    { subject: 'Sciences Numériques (SNT)', code: 'SNTEC', teacher: 'DIOP CHEIKH' },
    { subject: 'SVT', code: 'SVT', teacher: 'LABBE VERONIQUE' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'BONNET Sarah' },
  ],
  '205': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'RISI Enzo' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'MAGNE Andréa' },
    { subject: 'Atelier Théâtre', code: 'THEAT', teacher: 'CARRICHON Nicolas' },
    { subject: 'Cinéma-Audiovisuel', code: 'CI-AV', teacher: 'LAHAYE NICOLAS' },
    { subject: 'EPS', code: 'EPS', teacher: 'QUERE JOFFREY' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CUSSI Adelma' },
    { subject: 'Français', code: 'FR', teacher: 'SCHWANDER OLIVIER' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'PRIOUX Charles' },
    { subject: 'Langues et Cultures Anciennes', code: 'LCALA', teacher: 'KUBALA JAN' },
    { subject: 'Mathématiques', code: 'MATH', teacher: 'VERMEULEN GENEVIEVE' },
    { subject: 'Physique-Chimie', code: 'PC', teacher: 'MAHAUT Fabien' },
    { subject: 'SES', code: 'SES', teacher: 'NALBANT CORINNE' },
    { subject: 'Sciences Numériques (SNT)', code: 'SNTEC', teacher: 'DIOP CHEIKH' },
    { subject: 'SVT', code: 'SVT', teacher: 'MAUGENDRE CAROLE' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'SCHWANDER OLIVIER' },
  ],

  // Page 7
  '101': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'DANIEL Bertilla' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'HEUSSER SUSANNE' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CUSSI Adelma' },
    { subject: 'Français', code: 'FR', teacher: 'LESTANG Marie' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LOUIT Nicolas' },
    { subject: 'Enseignement scientifique', code: 'ES', teacher: 'MAUGENDRE CAROLE' },
    { subject: 'HGGSP', code: 'HGGSP', teacher: 'MAGONI Clizia' },
    { subject: 'HLP', code: 'HLPHI', teacher: 'ESLINGER GILLES' },
    { subject: 'Mathématiques Tronc Commun', code: 'MATH-TC', teacher: 'HENRIO CHRISTINE' },
    { subject: 'Mathématiques Spécialité', code: 'MATH', teacher: 'LACHAUX CLAUDE' },
    { subject: 'Physique-Chimie Spécialité', code: 'PC', teacher: 'VAGINAY FRANCINE' },
    { subject: 'SVT Spécialité', code: 'SVT', teacher: 'MATTARD JULIEN' },
    { subject: 'SES Spécialité', code: 'SES', teacher: 'NALBANT CORINNE' },
    { subject: 'NSI', code: 'NSINF', teacher: 'DIOP CHEIKH' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'LESTANG Marie' },
  ],
  '102': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'DANIEL Bertilla' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'HEUSSER SUSANNE' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'HOCINE Cécile' },
    { subject: 'Français', code: 'FR', teacher: 'KUBALA JAN' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LACOSTE AUDE-MARIE' },
    { subject: 'Enseignement scientifique', code: 'ES', teacher: 'MAUGENDRE CAROLE' },
    { subject: 'HGGSP', code: 'HGGSP', teacher: 'MAGONI Clizia' },
    { subject: 'HLP', code: 'HLPHI', teacher: 'ESLINGER GILLES' },
    { subject: 'Mathématiques Tronc Commun', code: 'MATH-TC', teacher: 'HENRIO CHRISTINE' },
    { subject: 'Mathématiques Spécialité', code: 'MATH', teacher: 'LACHAUX CLAUDE' },
    { subject: 'Physique-Chimie Spécialité', code: 'PC', teacher: 'VAGINAY FRANCINE' },
    { subject: 'SVT Spécialité', code: 'SVT', teacher: 'MATTARD JULIEN' },
    { subject: 'SES Spécialité', code: 'SES', teacher: 'NALBANT CORINNE' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'KUBALA JAN' },
  ],

  // Page 8
  '103': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'DANIEL Bertilla' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'HEUSSER SUSANNE' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CUSSI Adelma' },
    { subject: 'Français', code: 'FR', teacher: 'BESNARD SANDRA' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'PRIOUX Charles' },
    { subject: 'Enseignement scientifique', code: 'ES', teacher: 'VOVARD Frédérique' },
    { subject: 'HGGSP', code: 'HGGSP', teacher: 'MAGONI Clizia' },
    { subject: 'HLP', code: 'HLPHI', teacher: 'ESLINGER GILLES' },
    { subject: 'Mathématiques Tronc Commun', code: 'MATH-TC', teacher: 'HENRIO CHRISTINE' },
    { subject: 'Mathématiques Spécialité', code: 'MATH', teacher: 'LACHAUX CLAUDE' },
    { subject: 'Physique-Chimie Spécialité', code: 'PC', teacher: 'VAGINAY FRANCINE' },
    { subject: 'SVT Spécialité', code: 'SVT', teacher: 'MATTARD JULIEN' },
    { subject: 'SES Spécialité', code: 'SES', teacher: 'NALBANT CORINNE' },
    { subject: 'NSI', code: 'NSINF', teacher: 'DIOP CHEIKH' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'BESNARD SANDRA' },
  ],
  '104': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'DANIEL Bertilla' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'HEUSSER SUSANNE' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'CUSSI Adelma' },
    { subject: 'Français', code: 'FR', teacher: 'BOUTHONNIER Rémi' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'DIZABEAU ANNE' },
    { subject: 'Enseignement scientifique', code: 'ES', teacher: 'VOVARD Frédérique' },
    { subject: 'HGGSP', code: 'HGGSP', teacher: 'MAGONI Clizia' },
    { subject: 'HLP', code: 'HLPHI', teacher: 'ESLINGER GILLES' },
    { subject: 'Mathématiques Tronc Commun', code: 'MATH-TC', teacher: 'HENRIO CHRISTINE' },
    { subject: 'Mathématiques Spécialité', code: 'MATH', teacher: 'LACHAUX CLAUDE' },
    { subject: 'Physique-Chimie Spécialité', code: 'PC', teacher: 'VAGINAY FRANCINE' },
    { subject: 'SVT Spécialité', code: 'SVT', teacher: 'MATTARD JULIEN' },
    { subject: 'SES Spécialité', code: 'SES', teacher: 'NALBANT CORINNE' },
    { subject: 'NSI', code: 'NSINF', teacher: 'DIOP CHEIKH' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'BOUTHONNIER Rémi' },
  ],

  // Page 9
  'T01': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'LESURE Adrien' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'MAGNE Andréa' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'GONZALEZ Claire' },
    { subject: 'Philosophie', code: 'PHILO', teacher: 'ESLINGER GILLES' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'PRIOUX Charles' },
    { subject: 'Enseignement scientifique', code: 'ES', teacher: 'MAUGENDRE CAROLE' },
    { subject: 'HGGSP', code: 'HGGSP', teacher: 'CARRICHON Nicolas' },
    { subject: 'HLP', code: 'HLPHI', teacher: 'ESLINGER GILLES' },
    { subject: 'Mathématiques Spécialité', code: 'MATH', teacher: 'GUEDJ GUILLAUME' },
    { subject: 'Maths Expertes', code: 'MATEX', teacher: 'THIAUDE PHILIPPE' },
    { subject: 'Maths Complémentaires', code: 'MATCO', teacher: 'BACQUET GILLES' },
    { subject: 'Physique-Chimie Spécialité', code: 'PC', teacher: 'MAHAUT Fabien' },
    { subject: 'SVT Spécialité', code: 'SVT', teacher: 'LABBE VERONIQUE' },
    { subject: 'SES Spécialité', code: 'SES', teacher: 'NALBANT CORINNE' },
    { subject: 'NSI', code: 'NSINF', teacher: 'DIOP CHEIKH' },
    { subject: 'Droit et Grands Enjeux', code: 'DGEMC', teacher: 'MENDEL Gregor' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'PRIOUX Charles' },
  ],
  'T02': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'LESURE Adrien' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'MAGNE Andréa' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'GONZALEZ Claire' },
    { subject: 'Philosophie', code: 'PHILO', teacher: 'ESLINGER GILLES' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'LEPENNEC JEAN' },
    { subject: 'Enseignement scientifique', code: 'ES', teacher: 'MAUGENDRE CAROLE' },
    { subject: 'HLP', code: 'HLPHI', teacher: 'ESLINGER GILLES' },
    { subject: 'Mathématiques Spécialité', code: 'MATH', teacher: 'GUEDJ GUILLAUME' },
    { subject: 'Maths Expertes', code: 'MATEX', teacher: 'THIAUDE PHILIPPE' },
    { subject: 'Maths Complémentaires', code: 'MATCO', teacher: 'BACQUET GILLES' },
    { subject: 'Physique-Chimie Spécialité', code: 'PC', teacher: 'MAHAUT Fabien' },
    { subject: 'SES Spécialité', code: 'SES', teacher: 'NALBANT CORINNE' },
    { subject: 'Droit et Grands Enjeux', code: 'DGEMC', teacher: 'MENDEL Gregor' },
    { subject: 'Théâtre', code: 'THEAT', teacher: 'BOULANGER Alexis' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'LEPENNEC JEAN' },
  ],

  // Page 10
  'T03': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'LESURE Adrien' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'MAGNE Andréa' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'GONZALEZ Claire' },
    { subject: 'Philosophie', code: 'PHILO', teacher: 'BOULANGER Alexis' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'MAGONI Clizia' },
    { subject: 'Enseignement scientifique', code: 'ES', teacher: 'FAUQUEMBERG Claire' },
    { subject: 'Mathématiques Spécialité', code: 'MATH', teacher: 'GUEDJ GUILLAUME' },
    { subject: 'Maths Expertes', code: 'MATEX', teacher: 'THIAUDE PHILIPPE' },
    { subject: 'Maths Complémentaires', code: 'MATCO', teacher: 'BACQUET GILLES' },
    { subject: 'Physique-Chimie Spécialité', code: 'PC', teacher: 'MAHAUT Fabien' },
    { subject: 'SES Spécialité', code: 'SES', teacher: 'NALBANT CORINNE' },
    { subject: 'NSI', code: 'NSINF', teacher: 'DIOP CHEIKH' },
    { subject: 'Droit et Grands Enjeux', code: 'DGEMC', teacher: 'MENDEL Gregor' },
    { subject: 'Théâtre', code: 'THEAT', teacher: 'BOULANGER Alexis' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'MAGONI Clizia' },
  ],
  'T04': [
    { subject: 'Anglais LV1', code: 'AGL1', teacher: 'LESURE Adrien' },
    { subject: 'Allemand LV2', code: 'ALL2', teacher: 'MAGNE Andréa' },
    { subject: 'Espagnol LV2', code: 'ESP2', teacher: 'GONZALEZ Claire' },
    { subject: 'Philosophie', code: 'PHILO', teacher: 'ESLINGER GILLES' },
    { subject: 'Histoire-Géo', code: 'HG', teacher: 'MAGONI Clizia' },
    { subject: 'Enseignement scientifique', code: 'ES', teacher: 'FAUQUEMBERG Claire' },
    { subject: 'HGGSP', code: 'HGGSP', teacher: 'CARRICHON Nicolas' },
    { subject: 'Mathématiques Spécialité', code: 'MATH', teacher: 'THIAUDE PHILIPPE' },
    { subject: 'Maths Expertes', code: 'MATEX', teacher: 'THIAUDE PHILIPPE' },
    { subject: 'Maths Complémentaires', code: 'MATCO', teacher: 'BACQUET GILLES' },
    { subject: 'Physique-Chimie Spécialité', code: 'PC', teacher: 'MAHAUT Fabien' },
    { subject: 'SVT Spécialité', code: 'SVT', teacher: 'LABBE VERONIQUE' },
    { subject: 'SES Spécialité', code: 'SES', teacher: 'NALBANT CORINNE' },
    { subject: 'Droit et Grands Enjeux', code: 'DGEMC', teacher: 'MENDEL Gregor' },
    { subject: 'Théâtre', code: 'THEAT', teacher: 'BOULANGER Alexis' },
    { subject: 'Vie de classe', code: 'VIE', teacher: 'MAHAUT Fabien' },
  ]
};



export function applyOfficialPedagogicalAssignments(db: any) {
  let totalAssigned = 0;
  let teamsCreated = 0;

  function findTeacher(nameStr: string): UserItem | null {
    const clean = nameStr.replace(/^(m\.|mme)\s+/i, "").trim();
    const parts = clean.split(/\s+/);
    const lastName = parts[0].toLowerCase();
    const firstName = parts.slice(1).join(" ").toLowerCase();

    let match = db.users.find((u: UserItem) => u.role === "teacher" && (u.lastName || "").toLowerCase() === lastName);
    if (match) return match;

    match = db.users.find((u: UserItem) => u.role === "teacher" && (u.email || "").toLowerCase().includes(lastName));
    if (match) return match;

    match = db.users.find((u: UserItem) => u.role === "teacher" && (u.lastName || "").toLowerCase().includes(lastName));
    if (match) return match;

    if (firstName) {
      match = db.users.find((u: UserItem) => u.role === "teacher" && (u.firstName || "").toLowerCase().includes(firstName) && (u.lastName || "").toLowerCase().includes(lastName));
      if (match) return match;
    }
    return null;
  }

  for (const [classCode, items] of Object.entries(pedagogicalTeams)) {
    const classObj = db.classes.find((c: ClassItem) => c.code === classCode);
    const studentsCount = classObj?.studentCount || db.users.filter((u: UserItem) => u.classCode === classCode && u.role === "student" && u.status === "active").length;

    for (const item of items) {
      const teamName = classCode + "-" + item.subject;
      const teacher = findTeacher(item.teacher);

      if (item.code === "VIE" && classObj && teacher) {
        classObj.mainTeacher = teacher.firstName + " " + teacher.lastName;
      }

      let team = db.teams.find((t: TeamItem) => t.name === teamName);
      if (!team) {
        team = {
          id: "tm-" + classCode.toLowerCase() + "-" + item.code.toLowerCase().replace(/[^a-z0-9]/g, "") + "-" + Date.now().toString(36),
          m365TeamId: "",
          name: teamName,
          classCode: classCode,
          subjectCode: item.code,
          subjectName: item.subject,
          schoolYear: db.config?.currentSchoolYear || "2026-2027",
          memberCount: studentsCount,
          teacherCount: 0,
          assignedTeacherIds: [],
          assignedTeachers: [],
          status: "pending",
          autoManaged: true,
          isClassTeam: true,
          lastSync: "",
        };
        db.teams.push(team);
        teamsCreated++;
      } else {
        team.memberCount = studentsCount;
      }

      if (teacher) {
        team.assignedTeacherIds = [teacher.id];
        team.assignedTeachers = [{
          id: teacher.id,
          name: teacher.firstName + " " + teacher.lastName,
          email: teacher.email || teacher.upn,
        }];
        team.teacherCount = 1;
        totalAssigned++;
      }
    }
  }

  return { totalAssigned, teamsCreated, totalTeams: db.teams.length };
}
